
figure; hold on
%> Nodes and centers of the elements
plot(rr (1,:),rr (2,:),'o-','LineWidth',2), axis equal, grid on
plot(rrc(1,:),rrc(2,:),'rx','LineWidth',2,'MarkerSize',10)
%> Normal and tangent vectors
scalef = 0.07;
quiver(rrc(1,:),rrc(2,:),scalef*tvers(1,:), ...
                         scalef*tvers(2,:),'k','LineWidth',2'   , ...
                                               'MaxHeadSize',0.1, ...
                                               'AutoScale','off')
quiver(rrc(1,:),rrc(2,:),scalef*nvers(1,:), ...
                         scalef*nvers(2,:),'k','LineWidth',2'   , ...
                                               'MaxHeadSize',0.1, ...
                                               'AutoScale','off')
  
